[workspace]
resolver = "2"
members = [
    "joy-collection-utils",
    "joy-iter",
    # "wip-utils",
    # "old-macro",
    "joy-value-object",
    "joy-vector",
    "joy-macro",
    "joy-impl-ignore",
]
