[package]
name = "joy-macro"
version = "0.3.4"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1"
syn = { version = "2", features = ["extra-traits"] }
itertools = "0"